import tkinter as tk
from tkinter import ttk, filedialog
root = tk.Tk()
root.geometry('1000x800')
root.title("Soundboard")
root.configure(bg='#707070')
style = ttk.Style()
style.configure('TFrame', background='#707070')
frame = ttk.Frame(root, style='TFrame')
frame.columnconfigure(0, weight = 1, uniform='a')
frame.columnconfigure(1, weight = 1, uniform='a')
frame.columnconfigure(2, weight = 1, uniform='a')
frame.columnconfigure(3, weight = 1, uniform='a')
frame.columnconfigure(4, weight = 1, uniform='a')
frame.columnconfigure(5, weight = 1, uniform='a')
frame.columnconfigure(6, weight = 1, uniform='a')
frame.columnconfigure(7, weight = 1, uniform='a')
frame.columnconfigure(8, weight = 1, uniform='a')
frame.columnconfigure(9, weight = 1, uniform='a')
frame.rowconfigure(0, weight = 1, uniform = 'c')
frame.rowconfigure(1, weight = 1, uniform = 'c')
frame.rowconfigure(2, weight = 1, uniform = 'c')
frame.rowconfigure(3, weight = 1, uniform = 'c')
frame.rowconfigure(4, weight = 1, uniform = 'c')
frame.rowconfigure(5, weight = 1, uniform = 'c')
frame.rowconfigure(6, weight = 1, uniform = 'c')
frame.rowconfigure(7, weight = 1, uniform = 'c')
frame.pack(fill='both', expand=True)
button = ttk.Button(frame, text="Click Me!")
button.grid(column=0, row=0, sticky="nsew")
root.mainloop()